### ISSUE TITLE
[RFC] Routes JSON manifest

### ISSUE THREAD

**Issue by mrbut** [team-bimmer/ribbit#16]
# What?
An approach for the JSON manifest file that maps routes to components.

# Why?
In order to ensure that we do not need to traverse through files to map components ourselves (because it's slow) and also ensure that users will be able

# How?
When a user runs `ribbit` or `ribbit init` on the command line and generates a new **ribbit.config.js** file an additional file will be created in the `EntryParentFolder` [#15]. The default file contains an example of how the user can map a component to a route.

```
[
  {
    "route": "/",
    "assetName" : "index",
    "component": "./Home.js"
  },
  {
    "route": "/about/contact",
    "component": "./Contact.js"
  }
]
```

When the user runs the `ribbit b` or `ribbit build` command the CLI will then take that file and generate a new manifest file that points to routes to the newly generated static web pages. Additionally the parent directory of the asset with be the output path specified by the user in the Ribbit config file.

```
[
  {
    "route": "/",
    "asset": "dist/index.html"
  },
  {
    "route": "/about/contact",
    "asset": "dist/contact.html"
  }
]
```

### Route [string] (required)
The request route that will be sent from the client side to the server.

### AssetName [string] (optional)
Allows the user to set the names for a generated static web page. 

Ex. By default the static web asset is a `.toLowerCase` version of the original component's file name. So, `Home.js` would generate a `home.html` static asset. A user who would like the home to be named "index.html" can utilize the `assetName` property to produce an asset named "index.html" instead of "home.html".

```
assetName: 'index'
```

### Asset [string] (required)
A relative path that maps to the component that will generate a static asset.

# Additional Notes
Relates to #4

**Comment by 01212** [comment]
@mrbut : Malika, so what option in ribbit.config.js would the routes be listed under?

**Comment by brianwhon** [comment]
approve

**Comment by ramraphael** [comment]
Approved, Malika.

**Comment by 01212** [comment]
Approved
